name: Must run on custom runner

on: push

jobs:
  Testing-checkov:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello cloud gurus'
      - run: echo $HOSTNAME
      - run: pwd;ls -l; chmod 777 ../test-file.sh
      - run: ./test-file.sh
