name: Must run on custom runner

on: 
  push:
      branches:
        - main

jobs:
  Testing-Annotations:
    runs-on: ubuntu-latest
    steps:
      #- run: echo 'hello cloud gurus'
      #- run: echo $HOSTNAME
      - uses: actions/checkout@v2
      - run: chmod 777 test-file.sh
      - run: ./test-file.sh
