name: Must run on custom runner

on: push

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello cloud gurus'
      - run: echo $HOSTNAME
            # Call my powerful action!

