name: Must run on custom runner

on: 
  push:
      branches:
        - main  
  pull_request:
      branches:
        - main

# jobs:
#   Testing-Annotations:
#     runs-on: ubuntu-latest
#     steps:
#       #- run: echo 'hello cloud gurus'
#       #- run: echo $HOSTNAME
#       - uses: actions/checkout@v2
#       - run: chmod 777 test-file.sh
#       - run: ./test-file.sh
#       - run: echo "::warning file=missing_annotations ::Missing semicolon"
jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA Tests
      run: opa test tests/*.rego -v
  conftest:
    runs-on: ubuntu-latest
    container: openpolicyagent/conftest:latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Validate Kubernetes policy
        id: label_check
   #     continue-on-error: true
        run: |
          conftest test -o github -p tests/policy *.yaml
      - name: Display missing label warning
        if: ${{ failure() && steps.label_check.conclusion == 'failure' }}
        run: echo "::warning ::Missing labels in Yaml file"
