name: Must run on custom runner

on: push

jobs:
  Testing-checkov:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello cloud gurus'
      - run: echo $HOSTNAME
      - uses: actions/checkout@v2
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: test-labels
   #       framework: kubernetes
      - run: chmod 777 test-file.sh
      - run: ./test-file.sh
