name: Run OPA Check for Tagging & Annotation

on: 
  push:
      branches:
        - main  
  pull_request:
      branches:
        - main

jobs:
  # Check-Tagging-and-Annotations :
  #   runs-on: ubuntu-latest
  #   container: openpolicyagent/conftest:latest
  #   steps:
  #     - name: Code checkout
  #       uses: actions/checkout@v2
  #     - name: Validate Kubernetes policy
  #       id: label_check
  #       run: |
  #         conftest test -o github -p tests/policy *.yaml

  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA Tests
      run: opa eval --data tests/policy/test_k8s.rego -i input_data/test.yaml data.main -f pretty --fail-defined