name: Must run on custom runner

on: push

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello cloud gurus'
      - run: echo $HOSTNAME
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: test-labels
          framework: kubernetes 

