name: Check Tagging & Annotation

on: 
  push:
      branches:
        - main  
  pull_request:
      branches:
        - main

jobs:
  Check-Tagging-and-Annotations :
    runs-on: ubuntu-latest
    container: openpolicyagent/conftest:latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Validate Kubernetes policy
        id: label_check
        run: |
          conftest test -o github -p tests/policy *.yaml
