name: Run OPA Check for Tagging & Annotation

on: 
  push:
      branches:
        - main  
  pull_request:
      branches:
        - main

jobs:
  Check-Tagging-and-Annotations :
    runs-on: ubuntu-latest
    container: openpolicyagent/conftest:latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          repository: OpenGov/opa-policies
          path: policy
      # - name: test OPA repository
      #   run: |
      #     ls -l policy
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Run OPA test (conftest)
        id: label_check
        run: |
          conftest test -o github -p tests/policy input_data/*
      - name: Display missing label warning
        if: ${{ steps.label_check.outcome != 'success' }}
        run: echo "::warning ::Missing labels/annotations in Yaml"

  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA Tests
      run: opa eval --data tests/policy/test_k8s.rego -i input_data/test2.yaml data.main -f pretty --fail-defined